codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 11

coverage:
  precision: 1
  round: down
  range: "75...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "diff,files,footer"
  behavior: default
  require_changes: no
  after_n_builds: 11
